[package]
name = "advent"
version = "0.1.0"
authors = ["Charles Roussel <c.roussel@criteo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
dirs = "2.0"
failure = "0.1"
reqwest = "0.10.0-alpha.2"
tokio = "0.2.0-alpha.6"
criterion = "0.3"
itertools = "0.8"
num = "0.2"
nom = "5.0"
termion = "*"